// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import KeyboardArrowDown from "@mui/icons-material/KeyboardArrowDown";

var ChevronDownIcon = {};

function ChevronDownIcon$1(props) {
  return JsxRuntime.jsx(KeyboardArrowDown, {});
}

var make = ChevronDownIcon$1;

export {
  ChevronDownIcon ,
  make ,
}
/* react/jsx-runtime Not a pure module */
