// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import ExpandMore from "@mui/icons-material/ExpandMore";

var ExpandMoreIcon = {};

function ExpandMoreIcon$1(props) {
  return JsxRuntime.jsx(ExpandMore, {});
}

var make = ExpandMoreIcon$1;

export {
  ExpandMoreIcon ,
  make ,
}
/* react/jsx-runtime Not a pure module */
