// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import GitHub from "@mui/icons-material/GitHub";

var GitHubIcon = {};

function GitHubIcon$1(props) {
  return JsxRuntime.jsx(GitHub, {});
}

var make = GitHubIcon$1;

export {
  GitHubIcon ,
  make ,
}
/* react/jsx-runtime Not a pure module */
