// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function EnterPin(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
                              alt: "Description of image",
                              src: "/EnterPinTop.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
                              alt: "Description of image",
                              src: "/Pin.svg"
                            })
                      ],
                      className: "flex flex-col h-full gap-6"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Confirm & Pay",
                              className: " bg-[#E31837] text-white rounded-lg w-full h-10",
                              onClick: props.handleNavigate
                            }),
                        JsxRuntime.jsx("img", {
                              className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
                              alt: "Description of image",
                              src: "/KeypadIphone.svg"
                            })
                      ],
                      className: "flex flex-col gap-4"
                    })
              ],
              className: "flex flex-col h-full justify-between "
            });
}

var make = EnterPin;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
