// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Header from "../../Components/Header.res.mjs";
import * as AccountCard from "../../Components/AccountCard.res.mjs";
import * as BankAccountCard from "../../Components/BankAccountCard.res.mjs";
import * as TransactionsList from "../../Components/TransactionsList.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Home(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {}),
                JsxRuntime.jsx(AccountCard.make, {}),
                JsxRuntime.jsx("div", {
                      children: "Bank Accounts",
                      className: "my-2"
                    }),
                JsxRuntime.jsx(BankAccountCard.make, {
                      handleNavigate: (function () {
                          handleNavigate();
                        })
                    }),
                JsxRuntime.jsx("div", {
                      children: "All Transactions",
                      className: "my-2"
                    }),
                JsxRuntime.jsx(TransactionsList.make, {})
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Home;

export {
  make ,
}
/* Header Not a pure module */
