// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Header from "../../Components/Header.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as AccountCard from "../../Components/AccountCard.res.mjs";
import * as ExampleData from "../../Utilities/ExampleData.res.mjs";
import * as BankAccountCard from "../../Components/BankAccountCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as TransactionHistoryItem from "../../Components/TransactionHistoryItem.res.mjs";

function Home(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {}),
                JsxRuntime.jsx(AccountCard.make, {}),
                JsxRuntime.jsx("div", {
                      children: "Bank Accounts"
                    }),
                JsxRuntime.jsx(BankAccountCard.make, {
                      handleNavigate: (function () {
                          handleNavigate();
                        })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "All Transactions"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Belt_Array.map(ExampleData.contactOptions, (function (option) {
                                      return JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsx(TransactionHistoryItem.make, {
                                                          contact: option
                                                        }),
                                                    JsxRuntime.jsx("div", {
                                                          className: "border-t border-dashed w-full mt-6 border-[#E6E6E6]"
                                                        })
                                                  ],
                                                  className: "mt-6"
                                                }, option.id);
                                    }))
                            })
                      ]
                    })
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Home;

export {
  make ,
}
/* Header Not a pure module */
