// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../Components/Input.res.mjs";
import * as React from "react";
import * as BankOption from "../../Components/BankOption.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ExampleData from "../../Utilities/ExampleData.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function Transfer(props) {
  var handleNavigate = props.handleNavigate;
  var option = ExampleData.bankOptions[0];
  var firstOptionId = option !== undefined ? option.id : "";
  var match = React.useState(function () {
        return firstOptionId;
      });
  var setSelectedOption = match[1];
  var selectedOption = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(HeaderWithBack.make, {
                      title: "Transfer"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Who are you sending to?",
                              className: "font-bold text-lg"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(SecuredByFinterest.make, {}),
                              className: "flex justify-start"
                            })
                      ],
                      className: "flex flex-col gap-1 my-3 "
                    }),
                JsxRuntime.jsx(Input.make, {
                      placeholder: "Enter mobile number/name/account",
                      className: " p-2 text-base border border-[#E6E6E6]  rounded-lg text-sm"
                    }),
                JsxRuntime.jsx("div", {
                      children: Belt_Array.map(ExampleData.contactOptions, (function (option) {
                              var isSelected = selectedOption === option.id;
                              return JsxRuntime.jsxs("div", {
                                          children: [
                                            JsxRuntime.jsx(BankOption.make, {
                                                  onClick: (function (param) {
                                                      setSelectedOption(function (param) {
                                                            return option.id;
                                                          });
                                                    }),
                                                  isSelected: isSelected,
                                                  options: {
                                                    TAG: "ContactOptions",
                                                    _0: option
                                                  },
                                                  showBankDetails: false
                                                }),
                                            isSelected ? JsxRuntime.jsx("button", {
                                                    children: "Proceed",
                                                    className: "bg-[#00B76A] text-white rounded-lg w-full h-10 mt-4",
                                                    onClick: (function (param) {
                                                        handleNavigate();
                                                      })
                                                  }) : null,
                                            JsxRuntime.jsx("div", {
                                                  className: "border-t border-dashed w-full mt-6 border-[#E6E6E6]"
                                                })
                                          ],
                                          className: "mt-6"
                                        }, option.id);
                            }))
                    })
              ],
              className: "flex flex-col h-full gap-4 "
            });
}

var make = Transfer;

export {
  make ,
}
/* Input Not a pure module */
