// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TransactionCompleted(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
                      alt: "Description of image",
                      src: "/TransactionSuccessful.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "View in Wallet",
                              className: " bg-[#00B76A] text-white rounded-lg w-full h-10 text-sm",
                              onClick: props.handleNavigate
                            }),
                        JsxRuntime.jsx("div", {
                              children: "View Transaction History",
                              className: "flex items-center justify-center text-sm text-[#00B76A] w-full my-4"
                            })
                      ]
                    })
              ],
              className: "flex flex-col justify-between h-full "
            });
}

var make = TransactionCompleted;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
