// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../Components/Input.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function Transfer(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(HeaderWithBack.make, {
                      title: "Transfer"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Who are you sending to?",
                              className: "font-bold text-lg"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(SecuredByFinterest.make, {}),
                              className: "flex justify-start"
                            })
                      ],
                      className: "flex flex-col gap-1 my-3 "
                    }),
                JsxRuntime.jsx(Input.make, {
                      placeholder: "Enter mobile number/name/account",
                      className: " p-2 text-base border border-[#E6E6E6]  rounded-lg text-sm"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/RecentTransactionsHeader.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/SelectedContact.svg"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("button", {
                                    children: "Proceed",
                                    className: "bg-[#00B76A] text-white rounded-lg w-4/5 h-10",
                                    onClick: props.onNavigateToEnterAmount
                                  }),
                              className: "flex justify-end"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact1.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact2.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact3.svg"
                            })
                      ],
                      className: "flex flex-col gap-3 mt-2"
                    })
              ],
              className: "flex flex-col h-full gap-4 "
            });
}

var make = Transfer;

export {
  make ,
}
/* Input Not a pure module */
