// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Transfer(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/TransferHeader.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/SendingToHeader.svg"
                            })
                      ]
                    }),
                JsxRuntime.jsx("input", {
                      className: " p-2 text-base border border-[#E6E6E6]  rounded-lg text-sm",
                      placeholder: "Enter mobile number/name/account"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/RecentTransactionsHeader.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/SelectedContact.svg"
                            }),
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx("button", {
                                    children: "Proceed",
                                    className: "bg-[#00B76A] text-white rounded-lg w-4/5 h-10",
                                    onClick: props.onNavigateToEnterAmount
                                  }),
                              className: "flex justify-end"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact1.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact2.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/DottedDivider.svg"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/Contact3.svg"
                            })
                      ],
                      className: "flex flex-col gap-3 mt-2"
                    })
              ],
              className: "flex flex-col h-full gap-4 "
            });
}

var make = Transfer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
