// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BankAccountLinked(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
                      alt: "Description of image",
                      src: "/BankAccountLinkedSuccessfully.svg"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: "Next",
                            className: " bg-[#00B76A] text-white rounded-lg w-full h-10 text-sm"
                          })
                    })
              ],
              className: "flex flex-col justify-between h-full "
            });
}

var make = BankAccountLinked;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
