// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function FaceID(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("img", {
                    alt: "Description of image",
                    src: "/FaceID.svg"
                  }),
              className: "flex h-full w-full"
            });
}

var make = FaceID;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
