// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function LinkBankAccount(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Bank"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Link Bank Account",
                                      className: "font-bold text-xl"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Follow the below steps to add your default bank accounts",
                                      className: "font-light text-sm mt-4"
                                    })
                              ],
                              className: ""
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/SelectBankStepper.svg"
                            })
                      ],
                      className: "flex flex-col gap-10"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Complete",
                              className: " bg-[#00B76A] text-white rounded-lg w-full h-10",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {})
                      ],
                      className: "flex flex-col gap-4"
                    })
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = LinkBankAccount;

export {
  make ,
}
/* HeaderWithBack Not a pure module */
