// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../Components/Input.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";
import Checkbox from "@mui/material/Checkbox";

function OnboardingLogin(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Hey!",
                                      className: "font-bold text-4xl text-[#00B76A]"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Welcome to Finternet",
                                              className: "font-bold text-xl"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Access all assets via a unified interface and unlock the potential of seamless global transactions",
                                              className: "font-light text-sm mt-4"
                                            })
                                      ],
                                      className: "mt-10 "
                                    })
                              ]
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Enter your mobile number",
                                      className: "font-medium text-base"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("img", {
                                                      alt: "Description of image",
                                                      src: "/IndiaFlag.svg"
                                                    }),
                                                JsxRuntime.jsx("div", {
                                                      children: "+91",
                                                      className: "font-normal text-base"
                                                    }),
                                                JsxRuntime.jsx("svg", {
                                                      children: JsxRuntime.jsx("path", {
                                                            d: "M5.58917 7.03844C5.37032 7.03882 5.15357 6.99595 4.95135 6.91229C4.74913 6.82862 4.56544 6.70582 4.41083 6.55094L0 2.13927L1.17833 0.960938L5.58917 5.37177L10 0.960938L11.1783 2.13927L6.7675 6.5501C6.61296 6.70514 6.4293 6.82809 6.22708 6.9119C6.02486 6.99571 5.80807 7.03871 5.58917 7.03844Z",
                                                            fill: "#00B76A"
                                                          }),
                                                      height: "8",
                                                      width: "12",
                                                      fill: "none",
                                                      viewBox: "0 0 12 8",
                                                      xmlns: "http://www.w3.org/2000/svg"
                                                    })
                                              ],
                                              className: "flex flex-row  ml-4 gap-2 items-center "
                                            }),
                                        JsxRuntime.jsx(Input.make, {
                                              placeholder: "Enter your mobile number"
                                            })
                                      ],
                                      className: "flex flex-row border border-[#E6E6E6] rounded-lg"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "An OTP will be sent to the linked mobile number for verification",
                                      className: "font-light text-sm"
                                    })
                              ],
                              className: "mt-14 gap-4 flex flex-col"
                            })
                      ]
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Checkbox, {
                                      style: {
                                        color: "#00B76A"
                                      },
                                      defaultChecked: true,
                                      size: "small"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "By registering, you accept our",
                                              className: "font-normal text-sm"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Terms of Use ",
                                              className: "font-normal text-sm text-[#00B76A]"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "&",
                                              className: "font-normal text-sm"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Privacy Policy",
                                              className: "font-normal text-sm text-[#00B76A]"
                                            })
                                      ],
                                      className: "flex flew-row flex-wrap gap-1 "
                                    })
                              ],
                              className: "flex flew-row "
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Verify",
                              className: " bg-[#00B76A] text-white rounded-lg w-full h-12",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {})
                      ],
                      className: "mt-14 gap-y-4 flex flex-col"
                    })
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = OnboardingLogin;

export {
  make ,
}
/* Input Not a pure module */
