// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BankOption from "../../Components/BankOption.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ExampleData from "../../Utilities/ExampleData.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function SelectedBankAccount(props) {
  var handleNavigate = props.handleNavigate;
  var option = ExampleData.bankOptions[0];
  var firstBankId = option !== undefined ? option.id : "";
  var match = React.useState(function () {
        return firstBankId;
      });
  var setSelectedBank = match[1];
  var selectedBank = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Select Account"
                            }),
                        JsxRuntime.jsx("div", {
                              children: Belt_Array.map(ExampleData.bankAccountOptions, (function (option) {
                                      var isSelected = selectedBank === option.id;
                                      return JsxRuntime.jsxs("div", {
                                                  children: [
                                                    JsxRuntime.jsx(BankOption.make, {
                                                          onClick: (function (param) {
                                                              setSelectedBank(function (param) {
                                                                    return option.id;
                                                                  });
                                                            }),
                                                          isSelected: isSelected,
                                                          bankDetails: option,
                                                          showBankDetails: false,
                                                          showCardNumber: true
                                                        }),
                                                    JsxRuntime.jsx("div", {
                                                          className: "border-t border-dashed w-full mt-6 border-[#E6E6E6]"
                                                        })
                                                  ],
                                                  className: "mt-6"
                                                }, option.id);
                                    }))
                            })
                      ],
                      className: "flex flex-col gap-7"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Tokenize Account",
                              className: " bg-[#00B76A] text-white rounded-lg w-full h-10",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {})
                      ],
                      className: "flex flex-col gap-4"
                    })
              ],
              className: "flex flex-col h-full  justify-between"
            });
}

var make = SelectedBankAccount;

export {
  make ,
}
/* react Not a pure module */
