// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../../Utilities/Colors.res.mjs";
import * as Header from "../../Components/Header.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function QRScreen(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {
                      isFinternet: true
                    }),
                JsxRuntime.jsx("div", {
                      children: "Identity verified successfully!",
                      className: "font-bold text-lg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Account Address",
                                      className: " font-light text-[#797979] text-xs"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("div", {
                                            children: "nandan@finternet",
                                            className: " text-base "
                                          }),
                                      className: "flex flex-row justify-between"
                                    })
                              ],
                              className: "w-11/12"
                            }),
                        JsxRuntime.jsx("img", {
                              className: "w-11/12 self-center",
                              alt: "Description of image",
                              src: "/QRCode.svg"
                            }),
                        JsxRuntime.jsx("div", {
                              children: "Welcome to the Finternet!",
                              className: "font-light text-[#797979] text-base"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Link Bank Accounts",
                              className: " bg-black text-white text-xs rounded-lg w-3/5 h-10",
                              onClick: (function (param) {
                                  if (handleNavigate !== undefined) {
                                    return handleNavigate();
                                  } else {
                                    console.log("No navigation function provided");
                                    return ;
                                  }
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.black
                            })
                      ],
                      className: "flex flex-col justify-between items-center w-full border border-gray-100 drop-shadow-md rounded-2xl py-3 gap-4 py-5"
                    })
              ],
              className: "flex flex-col h-full gap-7"
            });
}

var make = QRScreen;

export {
  make ,
}
/* Header Not a pure module */
