// Generated by ReScript, PLEASE EDIT WITH CARE


var colors = {
  finternetGreen: "#00B76A",
  propertyBlue: "#0091FF",
  white: "#FFFFFF",
  black: "#000000",
  gray: "#797979",
  gray2: "#595959",
  darkGray: "#515151"
};

export {
  colors ,
}
/* No side effect */
