// Generated by ReScript, PLEASE EDIT WITH CARE


var bankAccountTokenization = "Bank Account Tokenization";

var domesticMoneyTransfer = "Domestic Money Transfer";

var all = [
  bankAccountTokenization,
  domesticMoneyTransfer
];

var MoneyUseCases = {
  bankAccountTokenization: bankAccountTokenization,
  domesticMoneyTransfer: domesticMoneyTransfer,
  all: all
};

var propertyTokenization = "Property Tokenization";

var loanAgainstProperty = "Loan Against Property";

var all$1 = [
  propertyTokenization,
  loanAgainstProperty
];

var PropertyUseCases = {
  propertyTokenization: propertyTokenization,
  loanAgainstProperty: loanAgainstProperty,
  all: all$1
};

var helloWorld = "Hello World !";

var finternetOnboarding = "Finternet Onboarding";

var all$2 = [
  helloWorld,
  finternetOnboarding
];

var WebHome = {
  helloWorld: helloWorld,
  finternetOnboarding: finternetOnboarding,
  all: all$2
};

var adminDashboard = "Admin Dashboard";

var all$3 = [adminDashboard];

var TokenManager = {
  adminDashboard: adminDashboard,
  all: all$3
};

export {
  MoneyUseCases ,
  PropertyUseCases ,
  WebHome ,
  TokenManager ,
}
/* No side effect */
