// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function toJson(record) {
  var assetDict = Js_dict.fromArray([
        [
          "currency",
          record.asset.currency
        ],
        [
          "unit",
          record.asset.unit
        ],
        [
          "token_manager",
          record.asset.token_manager
        ]
      ]);
  return Js_dict.fromArray([
              [
                "sender",
                record.sender
              ],
              [
                "recipient",
                record.recipient
              ],
              [
                "asset",
                assetDict
              ],
              [
                "signature",
                record.signature
              ]
            ]);
}

function tokenizedBodyToJson(record) {
  var accountDetailsDict = Js_dict.fromArray([[
          "account_number",
          record.account_details.account_number
        ]]);
  return Js_dict.fromArray([
              [
                "token_manager",
                record.token_manager
              ],
              [
                "asset_type",
                record.asset_type
              ],
              [
                "currency",
                record.currency
              ],
              [
                "account_details",
                accountDetailsDict
              ]
            ]);
}

function tokenizedPropertyBodyToJson(record) {
  var propertyDetailsDict = Js_dict.fromArray([
        [
          "property_id",
          record.property_details.property_id
        ],
        [
          "property_registrar",
          record.property_details.property_registrar
        ]
      ]);
  var attestationsArray = Belt_Array.map(record.attestations, (function (attestation) {
          return Js_dict.fromArray([[
                        "certificate",
                        attestation.certificate
                      ]]);
        }));
  return Js_dict.fromArray([
              [
                "asset_type",
                record.asset_type
              ],
              [
                "property_details",
                propertyDetailsDict
              ],
              [
                "attestations",
                attestationsArray
              ]
            ]);
}

function propertyPledgeResultToJson(record) {
  return Js_dict.fromArray([
              [
                "status",
                record.status
              ],
              [
                "sanctioned_amount",
                record.sanctioned_amount
              ],
              [
                "id",
                record.id
              ]
            ]);
}

function toJsonJwtBody(jwtBody) {
  var slMpcSetupDict = Js_dict.fromArray([[
          "keygen",
          {}
        ]]);
  var payloadDict = Js_dict.fromArray([
        [
          "slMpcSetup",
          slMpcSetupDict
        ],
        [
          "timeout",
          jwtBody.payload.timeout
        ],
        [
          "time",
          jwtBody.payload.time
        ]
      ]);
  return Js_dict.fromArray([
              [
                "token",
                jwtBody.token
              ],
              [
                "payload",
                payloadDict
              ],
              [
                "uuid",
                jwtBody.uuid
              ]
            ]);
}

function toJsonKeyGenResponse(stats) {
  return Js_dict.fromArray([
              [
                "public_key",
                stats.public_key
              ],
              [
                "total_send",
                stats.total_send
              ],
              [
                "total_recv",
                stats.total_recv
              ],
              [
                "total_wait",
                stats.total_wait
              ],
              [
                "total_time",
                stats.total_time
              ]
            ]);
}

export {
  toJson ,
  tokenizedBodyToJson ,
  tokenizedPropertyBodyToJson ,
  propertyPledgeResultToJson ,
  toJsonJwtBody ,
  toJsonKeyGenResponse ,
}
/* No side effect */
