// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../../Utilities/Colors.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";
import Checkbox from "@mui/material/Checkbox";

function AttestVerifiableCredentials(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Add Property Documents",
                              backButtonStrokeColor: Colors.colors.propertyBlue
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Ownership Certificate",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Valuation",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "No Objection Certificate",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    })
                              ],
                              className: "flex flex-col gap-5"
                            })
                      ],
                      className: "flex flex-col gap-5"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      alt: "Description of image",
                                      src: "/Info.svg"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Your verifiable credentials are going to be issued by a registrar.",
                                      className: "text-xs font-light text-[" + Colors.colors.gray + "]"
                                    })
                              ],
                              className: "flex flex-row gap-2 w-10/12 bg-white p-2 rounded-xl drop-shadow-md self-center"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Add Property Documents",
                              className: " bg-[" + Colors.colors.propertyBlue + "] text-white rounded-lg w-full h-12",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "mt-14 gap-y-4 flex flex-col"
                    })
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = AttestVerifiableCredentials;

export {
  make ,
}
/* HeaderWithBack Not a pure module */
