// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../Components/Input.res.mjs";
import * as Colors from "../../Utilities/Colors.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";
import Checkbox from "@mui/material/Checkbox";

function PropertyDetailsForm(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Tokenize your Property",
                              backButtonStrokeColor: "#0091FF"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Property ID",
                                      className: " text-[#797979] text-xs"
                                    }),
                                JsxRuntime.jsx(Input.make, {
                                      placeholder: "AXMD1EED",
                                      className: " p-3 border border-[#E6E6E6] rounded-lg text-sm placeholder-text-sm"
                                    })
                              ],
                              className: "flex flex-col gap-2"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Property Registrar",
                                      className: " text-[#797979] text-xs"
                                    }),
                                JsxRuntime.jsx(Input.make, {
                                      placeholder: "State Property Registrar",
                                      className: " p-3 border border-[#E6E6E6] rounded-lg text-sm placeholder-text-sm "
                                    })
                              ],
                              className: "flex flex-col gap-2"
                            })
                      ],
                      className: "flex flex-col gap-10"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Checkbox, {
                                      style: {
                                        color: Colors.colors.propertyBlue
                                      },
                                      defaultChecked: true,
                                      size: "small"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: JsxRuntime.jsx("div", {
                                            children: "I hereby declare that the concerned property belongs to me and  is free of any encumbrance.",
                                            className: "font-normal text-xs text-[#797979]"
                                          }),
                                      className: "flex flew-row flex-wrap gap-1 "
                                    })
                              ],
                              className: "flex flew-row "
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Attest verifiable credentials",
                              className: " bg-[#0091FF] text-white rounded-lg w-full h-12",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "mt-14 gap-y-4 flex flex-col"
                    })
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = PropertyDetailsForm;

export {
  make ,
}
/* Input Not a pure module */
