// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../../Utilities/Colors.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";
import * as SuccessStatusWithText from "../../Components/SuccessStatusWithText.res.mjs";

function PropertyTokenizedStatus(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(SuccessStatusWithText.make, {
                      text: "You have successfully tokenized your Property",
                      color: "Blue"
                    }),
                JsxRuntime.jsx("img", {
                      alt: "Description of image",
                      src: "/PropertyCardBlue.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Go to Dashboard",
                              className: " bg-[" + Colors.colors.propertyBlue + "] text-white rounded-lg w-full h-10 text-sm",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "flex flex-col gap-5"
                    })
              ],
              className: "flex flex-col justify-end  h-full gap-14"
            });
}

var make = PropertyTokenizedStatus;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
