// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Colors from "../../Utilities/Colors.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";
import * as LinkToFinternetModal from "../../Components/LinkToFinternetModal.res.mjs";
import Checkbox from "@mui/material/Checkbox";

function ShareVerifiableCredentials(props) {
  var match = React.useState(function () {
        return false;
      });
  var setShowModal = match[1];
  var toggleModal = function () {
    setShowModal(function (prev) {
          return !prev;
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Attesting verifiable credentials",
                              backButtonStrokeColor: Colors.colors.propertyBlue
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Ownership",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Value",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "MOC",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx(Checkbox, {
                                              style: {
                                                color: Colors.colors.propertyBlue
                                              },
                                              defaultChecked: true,
                                              size: "small"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Personal Details",
                                              className: "font-bold self-center text-xs text-[" + Colors.colors.darkGray + "]"
                                            })
                                      ],
                                      className: "flex flew-row"
                                    })
                              ],
                              className: "flex flex-col gap-5"
                            })
                      ],
                      className: "flex flex-col gap-5"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "View Offers",
                              className: " bg-[" + Colors.colors.propertyBlue + "] text-white rounded-lg w-full h-12",
                              onClick: (function (param) {
                                  setShowModal(function (prev) {
                                        return !prev;
                                      });
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "mt-14 gap-y-4 flex flex-col"
                    }),
                JsxRuntime.jsx(LinkToFinternetModal.make, {
                      showModal: match[0],
                      toggleModal: toggleModal,
                      handleNavigate: props.handleNavigate,
                      text: "By proceeding your consent to sharing the selected verifiable credentials to a third party.",
                      buttonText: "Proceed"
                    })
              ],
              className: "flex flex-col h-full justify-between relative"
            });
}

var make = ShareVerifiableCredentials;

export {
  make ,
}
/* react Not a pure module */
