// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AccountCard from "../Components/AccountCard.res.mjs";
import * as BankAccountCard from "../Components/BankAccountCard.res.mjs";
import * as TransactionsList from "../Components/TransactionsList.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function FinternetHome(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("svg", {
                              children: [
                                JsxRuntime.jsx("path", {
                                      d: "M11.023 10.4776C12.3526 8.66576 15.2414 7.39603 17.4753 7.64158L20.9808 8.02691C23.2147 8.27246 23.9478 9.94031 22.6182 11.7522L16.0378 20.7192C14.7082 22.531 11.8194 23.8008 9.5855 23.5552L6.07997 23.1699C3.84607 22.9243 3.11299 21.2565 4.4426 19.4447L11.023 10.4776Z",
                                      fill: "url(#paint0_linear_704_1338)"
                                    }),
                                JsxRuntime.jsx("path", {
                                      d: "M8.988 3.28046C10.3176 1.46862 13.2064 0.198893 15.4403 0.444445L18.9458 0.829775C21.1797 1.07533 21.9128 2.74317 20.5832 4.55502L14.0028 13.5221C12.6732 15.3339 9.7844 16.6036 7.5505 16.3581L4.04497 15.9728C1.81107 15.7272 1.07799 14.0594 2.4076 12.2475L8.988 3.28046Z",
                                      fill: "url(#paint1_linear_704_1338)"
                                    }),
                                JsxRuntime.jsxs("defs", {
                                      children: [
                                        JsxRuntime.jsxs("linearGradient", {
                                              children: [
                                                JsxRuntime.jsx("stop", {
                                                      stopColor: "#00DD8B"
                                                    }),
                                                JsxRuntime.jsx("stop", {
                                                      offset: "1",
                                                      stopColor: "#009217"
                                                    })
                                              ],
                                              id: "paint0_linear_704_1338",
                                              gradientUnits: "userSpaceOnUse",
                                              x1: "12.5129",
                                              x2: "12.5129",
                                              y1: "0.414062",
                                              y2: "23.5856"
                                            }),
                                        JsxRuntime.jsxs("linearGradient", {
                                              children: [
                                                JsxRuntime.jsx("stop", {
                                                      stopColor: "#0AEDB0"
                                                    }),
                                                JsxRuntime.jsx("stop", {
                                                      offset: "1",
                                                      stopColor: "#7FFD00",
                                                      stopOpacity: "0.55"
                                                    })
                                              ],
                                              id: "paint1_linear_704_1338",
                                              gradientUnits: "userSpaceOnUse",
                                              x1: "17.193",
                                              x2: "15.3705",
                                              y1: "0.637001",
                                              y2: "17.2176"
                                            })
                                      ]
                                    })
                              ],
                              height: "24",
                              width: "26",
                              fill: "none",
                              viewBox: "0 0 26 24",
                              xmlns: "http://www.w3.org/2000/svg"
                            }),
                        JsxRuntime.jsxs("svg", {
                              children: [
                                JsxRuntime.jsx("path", {
                                      d: "M6.44101 11.1056C6.44101 7.62135 9.26548 4.79688 12.7497 4.79688C16.2338 4.79688 19.0583 7.62136 19.0583 11.1055V13.8987C19.0583 15.785 19.6317 17.6267 20.7025 19.1797H4.79688C5.86761 17.6267 6.44101 15.785 6.44101 13.8987V11.1056Z",
                                      stroke: "#00B76A",
                                      strokeWidth: "1.5"
                                    }),
                                JsxRuntime.jsx("path", {
                                      d: "M12.75 4.79724V2.63867",
                                      opacity: "0.4",
                                      stroke: "#00B76A",
                                      strokeWidth: "1.5"
                                    }),
                                JsxRuntime.jsx("path", {
                                      d: "M15.9785 19.1797V19.4101C15.9785 21.1932 14.5331 22.6386 12.75 22.6386C10.9669 22.6386 9.52148 21.1932 9.52148 19.4101V19.1797",
                                      opacity: "0.4",
                                      stroke: "#00B76A",
                                      strokeWidth: "1.5"
                                    })
                              ],
                              height: "26",
                              width: "26",
                              fill: "none",
                              viewBox: "0 0 26 26",
                              xmlns: "http://www.w3.org/2000/svg"
                            })
                      ],
                      className: "flex flex-row justify-between"
                    }),
                JsxRuntime.jsx(AccountCard.make, {}),
                JsxRuntime.jsx("div", {
                      children: "Bank Accounts",
                      className: "my-2"
                    }),
                JsxRuntime.jsx(BankAccountCard.make, {
                      handleNavigate: (function () {
                          handleNavigate();
                        })
                    }),
                JsxRuntime.jsx("div", {
                      children: "All Transactions",
                      className: "my-2"
                    }),
                JsxRuntime.jsx(TransactionsList.make, {})
              ]
            });
}

var make = FinternetHome;

export {
  make ,
}
/* AccountCard Not a pure module */
