// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../Utilities/Colors.res.mjs";
import * as Header from "../Components/Header.res.mjs";
import * as AppCard from "../Components/AppCard.res.mjs";
import * as AccountCard from "../Components/AccountCard.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function FinternetHome(props) {
  var handleNavigate = props.handleNavigate;
  var tmp;
  switch (props.flow) {
    case "EmptyHome" :
        tmp = JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      alt: "Background Image",
                      src: "/NoAppsLinkedImage.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "No apps linked",
                              className: "text-white"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Link Account",
                              className: "bg-white text-black text-xs rounded-lg w-36 h-8",
                              onClick: (function (param) {
                                  if (handleNavigate !== undefined) {
                                    return handleNavigate();
                                  } else {
                                    console.log("No navigation function provided");
                                    return ;
                                  }
                                })
                            })
                      ],
                      className: "flex flex-col gap-4 w-full items-center"
                    })
              ],
              className: "flex flex-col items-center border border-gray-100 rounded-2xl p-5"
            });
        break;
    case "HomeWithMyFin" :
        tmp = JsxRuntime.jsx(AppCard.make, {
              app: "MyFin",
              amount: "₹ 3000"
            });
        break;
    case "HomeWithMyFinAndMyProp" :
        tmp = JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(AppCard.make, {
                      app: "MyFin",
                      amount: "₹ 80,03,000"
                    }),
                JsxRuntime.jsx(AppCard.make, {
                      app: "MyProp",
                      amount: "₹ 80,00,000"
                    })
              ],
              className: "flex flex-col gap-3"
            });
        break;
    
  }
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(Header.make, {
                      isFinternet: true
                    }),
                JsxRuntime.jsx(AccountCard.make, {
                      iconColor: Colors.colors.white
                    }),
                JsxRuntime.jsx("div", {
                      children: "Linked Applications",
                      className: "my-2 text-white"
                    }),
                tmp
              ],
              className: "flex flex-col gap-4"
            });
}

var make = FinternetHome;

export {
  make ,
}
/* Header Not a pure module */
