// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function P4Wrapper(props) {
  return JsxRuntime.jsx("div", {
              children: props.children,
              className: props.flag ? "p-4" : ""
            });
}

var make = P4Wrapper;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
