// Generated by ReScript, PLEASE EDIT WITH CARE

import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function LinkCredentials(props) {
  var onNavigateToFillLoanApplication = props.onNavigateToFillLoanApplication;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(HeaderWithBack.make, {
                              title: "Link / Upload Credentials"
                            }),
                        JsxRuntime.jsx("img", {
                              alt: "Description of image",
                              src: "/LinkCredentials.svg"
                            })
                      ],
                      className: "flex flex-col gap-7"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Next",
                              className: " bg-[#00B76A] text-white rounded-lg w-full h-10",
                              onClick: (function (param) {
                                  onNavigateToFillLoanApplication();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {})
                      ],
                      className: "flex flex-col gap-4"
                    })
              ],
              className: "flex flex-col h-full  justify-between"
            });
}

var make = LinkCredentials;

export {
  make ,
}
/* HeaderWithBack Not a pure module */
