// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../../Utilities/Colors.res.mjs";
import * as Divider from "../../Components/Divider.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function LoanSanctionedSuccessfully(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("img", {
                                              alt: "Description of image",
                                              src: "/SuccessBlueSmall.svg"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "Loan Sanctioned",
                                              className: "font-bold text-base"
                                            })
                                      ],
                                      className: "flex flex-row gap-2 items-center"
                                    }),
                                JsxRuntime.jsx(Divider.make, {})
                              ],
                              className: "flex flex-col gap-3"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Your loans",
                                              className: "text-sm text-[" + Colors.colors.gray2 + "] "
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: JsxRuntime.jsx("div", {
                                                    children: "Add More",
                                                    className: "text-xs font-medium text-[" + Colors.colors.propertyBlue + "] "
                                                  }),
                                              className: "bg-lightBlue-rgba p-1 px-2 rounded-2xl"
                                            })
                                      ],
                                      className: "flex flex-row justify-between items-center mx-5"
                                    }),
                                JsxRuntime.jsx("img", {
                                      alt: "Description of image",
                                      src: "/PledgedCard.svg"
                                    })
                              ]
                            })
                      ],
                      className: "flex flex-col gap-5"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "View in Wallet",
                              className: " bg-[" + Colors.colors.propertyBlue + "] text-white rounded-lg w-full h-10 text-sm",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "flex flex-col gap-5"
                    })
              ],
              className: "flex flex-col justify-between h-full gap-14"
            });
}

var make = LoanSanctionedSuccessfully;

export {
  make ,
}
/* Divider Not a pure module */
