// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../../Utilities/Colors.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function LoanSanctionedSuccessfully(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: JsxRuntime.jsx("img", {
                                  alt: "Description of image",
                                  src: "/LoanDisbursedSuccesfully.svg"
                                })
                          }),
                      className: "flex flex-col gap-5"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "View in Wallet",
                              className: "bg-[" + Colors.colors.propertyBlue + "] text-white rounded-lg w-full h-10 text-sm",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            }),
                        JsxRuntime.jsx(SecuredByFinterest.make, {
                              color: Colors.colors.propertyBlue
                            })
                      ],
                      className: "flex flex-col gap-5"
                    })
              ],
              className: "flex flex-col justify-between h-full gap-14"
            });
}

var make = LoanSanctionedSuccessfully;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
