// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function SelectBankForLoan(props) {
  var onNavigateToFillLoanApplication = props.onNavigateToFillLoanApplication;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("img", {
                                            alt: "Description of image",
                                            src: "/BackIcon.svg"
                                          }),
                                      JsxRuntime.jsx("div", {
                                            children: "Select a Bank",
                                            className: "font-bold text-base"
                                          })
                                    ],
                                    className: "flex flex-row gap-2"
                                  }),
                              className: "flex flex-col gap-10"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("input", {
                                      className: " p-3 border border-[#E6E6E6]  rounded-lg text-sm placeholder-text-sm mb-4",
                                      placeholder: "Search bank"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("img", {
                                                      alt: "Description of image",
                                                      src: "/ABCBankSelected.svg"
                                                    }),
                                                JsxRuntime.jsx("button", {
                                                      children: "Continue",
                                                      className: " bg-[#00B76A] text-white rounded-lg w-full h-10",
                                                      onClick: (function (param) {
                                                          onNavigateToFillLoanApplication();
                                                        })
                                                    })
                                              ]
                                            }),
                                        JsxRuntime.jsx("img", {
                                              alt: "Description of image",
                                              src: "/UnselectedBanks.svg"
                                            })
                                      ]
                                    })
                              ],
                              className: "flex flex-col w-full my-7 "
                            })
                      ]
                    }),
                JsxRuntime.jsx(SecuredByFinterest.make, {})
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = SelectBankForLoan;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
