// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Input from "../../Components/Input.res.mjs";
import * as React from "react";
import * as BankOption from "../../Components/BankOption.res.mjs";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ExampleData from "../../Utilities/ExampleData.res.mjs";
import * as HeaderWithBack from "../../Components/HeaderWithBack.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as SecuredByFinterest from "../../Components/SecuredByFinterest.res.mjs";

function SelectBankForLoan(props) {
  var handleNavigate = props.handleNavigate;
  var option = ExampleData.bankOptions[0];
  var firstBankId = option !== undefined ? option.id : "";
  var match = React.useState(function () {
        return firstBankId;
      });
  var setSelectedBank = match[1];
  var selectedBank = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: JsxRuntime.jsx(HeaderWithBack.make, {
                                    title: "Select a Bank"
                                  }),
                              className: "flex flex-col gap-10"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Input.make, {
                                      placeholder: "Search bank",
                                      className: " p-3 border border-[#E6E6E6]  rounded-lg text-sm placeholder-text-sm mb-4"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: Belt_Array.map(ExampleData.bankOptions, (function (option) {
                                              var isSelected = selectedBank === option.id;
                                              return JsxRuntime.jsxs("div", {
                                                          children: [
                                                            JsxRuntime.jsx(BankOption.make, {
                                                                  onClick: (function (param) {
                                                                      setSelectedBank(function (param) {
                                                                            return option.id;
                                                                          });
                                                                    }),
                                                                  isSelected: isSelected,
                                                                  bankDetails: option
                                                                }),
                                                            isSelected ? JsxRuntime.jsx("button", {
                                                                    children: "Continue",
                                                                    className: "bg-[#00B76A] text-white rounded-lg w-full h-10 mt-4",
                                                                    onClick: (function (param) {
                                                                        handleNavigate();
                                                                      })
                                                                  }) : null,
                                                            JsxRuntime.jsx("div", {
                                                                  className: "border-t border-dashed w-full mt-6 border-[#E6E6E6]"
                                                                })
                                                          ],
                                                          className: "mt-6"
                                                        }, option.id);
                                            }))
                                    })
                              ],
                              className: "flex flex-col w-full my-7 "
                            })
                      ]
                    }),
                JsxRuntime.jsx(SecuredByFinterest.make, {})
              ],
              className: "flex flex-col h-full justify-between"
            });
}

var make = SelectBankForLoan;

export {
  make ,
}
/* Input Not a pure module */
