// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ExpandMoreIcon from "../Icons/ExpandMoreIcon.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import Accordion from "@mui/material/Accordion";
import AccordionDetails from "@mui/material/AccordionDetails";
import AccordionSummary from "@mui/material/AccordionSummary";

function toJson(record) {
  var assetDict = Js_dict.fromArray([
        [
          "currency",
          record.asset.currency
        ],
        [
          "unit",
          record.asset.unit
        ],
        [
          "token_manager",
          record.asset.token_manager
        ]
      ]);
  return Js_dict.fromArray([
              [
                "sender",
                record.sender
              ],
              [
                "recipient",
                record.recipient
              ],
              [
                "asset",
                assetDict
              ],
              [
                "signature",
                record.signature
              ]
            ]);
}

function Accordion$1(props) {
  var transactionResult = props.transactionResult;
  var transactionsHistory = props.transactionsHistory;
  var userAssets = props.userAssets;
  var userData = props.userData;
  var bodyJson = toJson({
        sender: "arnab.d@unifiedledger1",
        recipient: "ales@ledger",
        asset: {
          currency: "USD",
          unit: 200,
          token_manager: "tokenManagerAddress"
        },
        signature: "signature"
      });
  var prettyJson = JSON.stringify(userData, undefined, 2);
  var prettyTransactionsHistory = JSON.stringify(transactionsHistory, undefined, 2);
  var prettyAssets = JSON.stringify(userAssets, undefined, 2);
  var prettyTransactionResult = JSON.stringify(transactionResult, undefined, 2);
  var prettyPostBody = JSON.stringify(bodyJson, undefined, 2);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs(Accordion, {
                      children: [
                        JsxRuntime.jsx(AccordionSummary, {
                              "aria-controls": "panel1-content",
                              id: "panel1-header",
                              children: "Fetch User Details",
                              expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                            }),
                        JsxRuntime.jsxs(AccordionDetails, {
                              children: [
                                Caml_obj.notequal(userData, null) ? JsxRuntime.jsxs(Accordion, {
                                        className: "w-11/12 ",
                                        children: [
                                          JsxRuntime.jsx(AccordionSummary, {
                                                "aria-controls": "panel2-content",
                                                id: "panel2-header",
                                                children: "GET user",
                                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                                              }),
                                          JsxRuntime.jsx(AccordionDetails, {
                                                className: "text-sm",
                                                children: Caml_option.some(JsxRuntime.jsx("pre", {
                                                          children: prettyJson,
                                                          className: "whitespace-pre-wrap"
                                                        }))
                                              })
                                        ]
                                      }) : null,
                                Caml_obj.notequal(userAssets, null) ? JsxRuntime.jsxs(Accordion, {
                                        className: "w-11/12 ",
                                        children: [
                                          JsxRuntime.jsx(AccordionSummary, {
                                                "aria-controls": "panel2-content",
                                                id: "panel2-header",
                                                children: "GET assets",
                                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                                              }),
                                          JsxRuntime.jsx(AccordionDetails, {
                                                children: Caml_option.some(JsxRuntime.jsx("pre", {
                                                          children: prettyAssets,
                                                          className: "whitespace-pre-wrap"
                                                        }))
                                              })
                                        ]
                                      }) : null,
                                Caml_obj.notequal(transactionsHistory, null) ? JsxRuntime.jsxs(Accordion, {
                                        className: "w-11/12 ",
                                        children: [
                                          JsxRuntime.jsx(AccordionSummary, {
                                                "aria-controls": "panel2-content",
                                                id: "panel2-header",
                                                children: "GET transactionsList",
                                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                                              }),
                                          JsxRuntime.jsx(AccordionDetails, {
                                                children: Caml_option.some(JsxRuntime.jsx("pre", {
                                                          children: prettyTransactionsHistory,
                                                          className: "whitespace-pre-wrap"
                                                        }))
                                              })
                                        ]
                                      }) : null
                              ]
                            })
                      ]
                    }),
                props.showAuthInitiated ? JsxRuntime.jsxs(Accordion, {
                        children: [
                          JsxRuntime.jsx(AccordionSummary, {
                                "aria-controls": "panel1-content",
                                id: "panel1-header",
                                children: "Auth Initiated (Wallet)",
                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                              }),
                          JsxRuntime.jsx(AccordionDetails, {
                                className: "text-sm",
                                children: "Transaction signed through the wallet"
                              })
                        ]
                      }) : null,
                props.showTransactionConfirm ? JsxRuntime.jsxs(Accordion, {
                        children: [
                          JsxRuntime.jsx(AccordionSummary, {
                                "aria-controls": "panel1-content",
                                id: "panel1-header",
                                children: "Confirm Transaction",
                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                              }),
                          JsxRuntime.jsx(AccordionDetails, {
                                children: Caml_option.some(JsxRuntime.jsxs(Accordion, {
                                          className: "w-11/12 ",
                                          children: [
                                            JsxRuntime.jsx(AccordionSummary, {
                                                  "aria-controls": "panel2-content",
                                                  id: "panel2-header",
                                                  children: "POST https://finternet-app-api.shuttleapp.rs/v1/users/exampleUserId/assets/123/asset:transfer",
                                                  expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                                                }),
                                            JsxRuntime.jsx(AccordionDetails, {
                                                  className: "text-sm",
                                                  children: Caml_option.some(JsxRuntime.jsx("pre", {
                                                            children: prettyPostBody,
                                                            className: "whitespace-pre-wrap"
                                                          }))
                                                })
                                          ]
                                        }))
                              })
                        ]
                      }) : null,
                Caml_obj.notequal(transactionResult, null) ? JsxRuntime.jsxs(Accordion, {
                        children: [
                          JsxRuntime.jsx(AccordionSummary, {
                                "aria-controls": "panel1-content",
                                id: "panel1-header",
                                children: "GET Transaction Details",
                                expandIcon: Caml_option.some(JsxRuntime.jsx(ExpandMoreIcon.make, {}))
                              }),
                          JsxRuntime.jsx(AccordionDetails, {
                                className: "text-sm",
                                children: Caml_option.some(JsxRuntime.jsx("pre", {
                                          children: prettyTransactionResult,
                                          className: "whitespace-pre-wrap"
                                        }))
                              })
                        ]
                      }) : null
              ]
            });
}

var make = Accordion$1;

export {
  toJson ,
  make ,
}
/* ExpandMoreIcon Not a pure module */
