// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function AccountCard(props) {
  return JsxRuntime.jsx("img", {
              alt: "Description of image",
              src: "/CapitalMarket.svg"
            });
}

var make = AccountCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
