// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../Utilities/Colors.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function BankOption(props) {
  var __showCardNumber = props.showCardNumber;
  var __showBankDetails = props.showBankDetails;
  var bankDetails = props.bankDetails;
  var showBankDetails = __showBankDetails !== undefined ? __showBankDetails : true;
  var showCardNumber = __showCardNumber !== undefined ? __showCardNumber : false;
  var radioButtonPath = showBankDetails ? "/RadioButtonSelectedBlue.svg" : "/RadioButtonSelected.svg";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      alt: "Description of image",
                                      src: bankDetails.imagePath
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "w-px h-4 bg-[#E6E6E6] self-center"
                                    })
                              ],
                              className: "flex flex-row gap-2 "
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: bankDetails.name,
                                      className: " font-bold text-sm"
                                    }),
                                showBankDetails ? JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("div", {
                                                        children: "LTV ratio:",
                                                        className: "text-xs text-[" + Colors.colors.gray + "] font-medium"
                                                      }),
                                                  JsxRuntime.jsx("div", {
                                                        children: bankDetails.ltvRatio,
                                                        className: "text-xs  text-[" + Colors.colors.propertyBlue + "] font-bold"
                                                      })
                                                ],
                                                className: "flex flex-row gap-1"
                                              }),
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("div", {
                                                        children: "Interest:",
                                                        className: "text-xs text-[" + Colors.colors.gray + "] font-medium"
                                                      }),
                                                  JsxRuntime.jsx("div", {
                                                        children: bankDetails.interestRate,
                                                        className: "text-xs text-[" + Colors.colors.propertyBlue + "] font-bold"
                                                      })
                                                ],
                                                className: "flex flex-row justify-between gap-1"
                                              })
                                        ],
                                        className: "flex flex-row justify-between "
                                      }) : null,
                                showCardNumber ? JsxRuntime.jsx("div", {
                                        children: bankDetails.cardNumber
                                      }) : null
                              ],
                              className: "flex flex-col w-9/12 "
                            })
                      ],
                      className: "flex flex-row gap-3 w-11/12 "
                    }),
                props.isSelected ? JsxRuntime.jsx("img", {
                        alt: "Description of image",
                        src: radioButtonPath
                      }) : JsxRuntime.jsx("img", {
                        alt: "Description of image",
                        src: "/RadioButtonUnselected.svg"
                      })
              ],
              className: "flex flex-row justify-between mx-1 cursor-pointer  ",
              onClick: props.onClick
            });
}

var make = BankOption;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
