// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BankAccountCard(props) {
  var onNavigateToReceiversList = props.onNavigateToReceiversList;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: " h-auto p-5",
                      alt: "Description of image",
                      src: "/BankAccounts.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "p-5",
                              alt: "Description of image",
                              src: "/Balance.svg"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Transfer",
                              className: "bg-[#00B76A] text-white rounded-lg m-5 h-10 w-32 ",
                              onClick: (function (param) {
                                  onNavigateToReceiversList();
                                })
                            })
                      ],
                      className: "flex flex-row justify-between"
                    })
              ],
              className: "border border-gray-100 drop-shadow-md rounded-2xl "
            });
}

var make = BankAccountCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
