// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BankAccountCard(props) {
  var handleNavigate = props.handleNavigate;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: " h-auto p-5",
                      alt: "Description of image",
                      src: "/BankAccounts.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Balance",
                                      className: "font-extralight text-textGray"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "₹ 5000",
                                      className: "font-bold  text-xl"
                                    })
                              ]
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Transfer",
                              className: "bg-[#00B76A] text-white rounded-lg  h-10 w-32 ",
                              onClick: (function (param) {
                                  handleNavigate();
                                })
                            })
                      ],
                      className: "flex flex-row justify-between items-center mx-5 pb-5"
                    })
              ],
              className: "border border-gray-100  rounded-2xl "
            });
}

var make = BankAccountCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
