// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BankOption(props) {
  var bankDetails = props.bankDetails;
  console.log(bankDetails);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      alt: "Description of image",
                                      src: bankDetails.imagePath
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "w-px h-4 bg-[#E6E6E6] self-center"
                                    })
                              ],
                              className: "flex flex-row gap-2"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: bankDetails.name,
                                      className: " font-bold text-sm"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: bankDetails.description,
                                      className: " text-xs"
                                    })
                              ],
                              className: "flex flex-col "
                            })
                      ],
                      className: "flex flex-row gap-3"
                    }),
                props.isSelected ? JsxRuntime.jsx("img", {
                        alt: "Description of image",
                        src: "/RadioButtonSelected.svg"
                      }) : JsxRuntime.jsx("img", {
                        alt: "Description of image",
                        src: "/RadioButtonUnselected.svg"
                      })
              ],
              className: "flex flex-row justify-between mx-1 cursor-pointer ",
              onClick: props.onClick
            });
}

var make = BankOption;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
