// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function BlueHeader(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("svg", {
                      children: [
                        JsxRuntime.jsx("path", {
                              d: "M11.0229 10.4776C12.3525 8.66576 15.2413 7.39603 17.4752 7.64158L20.9807 8.02691C23.2146 8.27246 23.9477 9.94031 22.6181 11.7522L16.0377 20.7192C14.7081 22.531 11.8193 23.8008 9.58536 23.5552L6.07983 23.1699C3.84593 22.9243 3.11285 21.2565 4.44246 19.4447L11.0229 10.4776Z",
                              fill: "url(#paint0_linear_14_2842)"
                            }),
                        JsxRuntime.jsx("path", {
                              d: "M8.98786 3.28046C10.3175 1.46862 13.2063 0.198893 15.4402 0.444445L18.9457 0.829775C21.1796 1.07533 21.9127 2.74317 20.5831 4.55502L14.0027 13.5221C12.6731 15.3339 9.78427 16.6036 7.55036 16.3581L4.04484 15.9728C1.81093 15.7272 1.07785 14.0594 2.40746 12.2475L8.98786 3.28046Z",
                              fill: "url(#paint1_linear_14_2842)"
                            }),
                        JsxRuntime.jsxs("defs", {
                              children: [
                                JsxRuntime.jsxs("linearGradient", {
                                      children: [
                                        JsxRuntime.jsx("stop", {
                                              stopColor: "#0091FF"
                                            }),
                                        JsxRuntime.jsx("stop", {
                                              offset: "1",
                                              stopColor: "#220092",
                                              stopOpacity: "0.1"
                                            })
                                      ],
                                      id: "paint0_linear_14_2842",
                                      gradientUnits: "userSpaceOnUse",
                                      x1: "12.5128",
                                      x2: "12.5128",
                                      y1: "0.414062",
                                      y2: "23.5856"
                                    }),
                                JsxRuntime.jsxs("linearGradient", {
                                      children: [
                                        JsxRuntime.jsx("stop", {
                                              stopColor: "#0091FF"
                                            }),
                                        JsxRuntime.jsx("stop", {
                                              offset: "1",
                                              stopColor: "#220092",
                                              stopOpacity: "0.55"
                                            })
                                      ],
                                      id: "paint1_linear_14_2842",
                                      gradientUnits: "userSpaceOnUse",
                                      x1: "17.1929",
                                      x2: "15.3704",
                                      y1: "0.637001",
                                      y2: "17.2176"
                                    })
                              ]
                            })
                      ],
                      height: "24",
                      width: "26",
                      fill: "none",
                      viewBox: "0 0 26 24",
                      xmlns: "http://www.w3.org/2000/svg"
                    }),
                JsxRuntime.jsxs("svg", {
                      children: [
                        JsxRuntime.jsx("rect", {
                              height: "32",
                              width: "32",
                              fill: "#E6FFF4",
                              rx: "16"
                            }),
                        JsxRuntime.jsx("path", {
                              d: "M9.44101 14.1056C9.44101 10.6214 12.2655 7.79688 15.7497 7.79688C19.2338 7.79688 22.0583 10.6214 22.0583 14.1055V16.8987C22.0583 18.785 22.6317 20.6267 23.7025 22.1797H7.79688C8.86761 20.6267 9.44101 18.785 9.44101 16.8987V14.1056Z",
                              stroke: "#0091FF",
                              strokeOpacity: "0.8",
                              strokeWidth: "1.5"
                            }),
                        JsxRuntime.jsx("path", {
                              d: "M15.7498 7.79724V5.63867",
                              opacity: "0.4",
                              stroke: "#0091FF",
                              strokeOpacity: "0.8",
                              strokeWidth: "1.5"
                            }),
                        JsxRuntime.jsx("path", {
                              d: "M18.9787 22.1797V22.4101C18.9787 24.1932 17.5333 25.6386 15.7502 25.6386C13.9671 25.6386 12.5217 24.1932 12.5217 22.4101V22.1797",
                              opacity: "0.4",
                              stroke: "#0091FF",
                              strokeOpacity: "0.8",
                              strokeWidth: "1.5"
                            })
                      ],
                      height: "32",
                      width: "32",
                      fill: "none",
                      viewBox: "0 0 32 32",
                      xmlns: "http://www.w3.org/2000/svg"
                    })
              ],
              className: "flex flex-row justify-between"
            });
}

var make = BlueHeader;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
