// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Divider(props) {
  return JsxRuntime.jsx("div", {
              className: "border-t -mx-4 border-[#E6E6E6] drop-shadow "
            });
}

var make = Divider;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
