// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as JsxRuntime from "react/jsx-runtime";

function Drawer(props) {
  var selectedOption = props.selectedOption;
  var handleDrawerSelection = props.handleDrawerSelection;
  var moneyUseCases = [
    "User Onboarding",
    "Domestic Money Transfer"
  ];
  var propertyUseCases = [
    "Property User Onboarding",
    "Loan Against Property"
  ];
  var home = [
    "Hello World!",
    "Finternet Onboarding"
  ];
  var renderSection = function (title, items) {
    return JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("div", {
                        children: title,
                        className: "font-bold"
                      }),
                  Belt_Array.map(items, (function (item) {
                          return JsxRuntime.jsx("div", {
                                      children: item,
                                      className: "cursor-pointer p-2 rounded " + (
                                        selectedOption === item ? "bg-gray-100" : "bg-white "
                                      ),
                                      onClick: (function (param) {
                                          handleDrawerSelection(item);
                                        })
                                    }, item);
                        })),
                  JsxRuntime.jsx("hr", {
                        className: "mt-2 p-1"
                      })
                ],
                className: "flex flex-col gap-2"
              });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                renderSection("Home", home),
                renderSection("Money use cases", moneyUseCases),
                renderSection("Property use cases (Coming Soon)", propertyUseCases)
              ],
              className: "flex flex-col gap-4 w-64 hidden sm:block border-r h-full p-4"
            });
}

var make = Drawer;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
