// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as JsxRuntime from "react/jsx-runtime";
import Select from "@mui/material/Select";
import MenuItem from "@mui/material/MenuItem";
import FormControl from "@mui/material/FormControl";

function Dropdown(props) {
  var match = React.useState(function () {
        return "Tickets";
      });
  var setOption = match[1];
  var handleChange = function (e, param) {
    setOption(e.target.value);
  };
  return JsxRuntime.jsx(FormControl, {
              children: Caml_option.some(JsxRuntime.jsxs(Select, {
                        id: "demo-simple-select",
                        value: match[0],
                        children: [
                          JsxRuntime.jsx(MenuItem, {
                                children: "Tickets",
                                value: "Tickets"
                              }),
                          JsxRuntime.jsx(MenuItem, {
                                children: "Books",
                                value: "Books"
                              }),
                          JsxRuntime.jsx(MenuItem, {
                                children: "Food",
                                value: "Food"
                              })
                        ],
                        onChange: handleChange,
                        sx: [{
                            borderRadius: 4.0
                          }]
                      })),
              fullWidth: true
            });
}

var make = Dropdown;

export {
  make ,
}
/* react Not a pure module */
