// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function HeaderWithBack(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      alt: "Description of image",
                      src: "/BackIcon.svg"
                    }),
                JsxRuntime.jsx("div", {
                      children: props.title,
                      className: "font-bold text-base"
                    })
              ],
              className: "flex flex-row gap-2"
            });
}

var make = HeaderWithBack;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
