// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as JsxRuntime from "react/jsx-runtime";

function Input(props) {
  return JsxRuntime.jsx("input", {
              className: Belt_Option.getWithDefault(props.className, "flex-1 p-2 text-base outline-none rounded-lg w-4/5 text-sm"),
              placeholder: props.placeholder
            });
}

var make = Input;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
