// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function LinkToFinternetModal(props) {
  var handleNavigate = props.handleNavigate;
  var toggleModal = props.toggleModal;
  if (props.showModal) {
    return JsxRuntime.jsx("div", {
                children: JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: props.text,
                              className: "text-sm text-center "
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Cancel",
                                      className: "bg-white border border-[#0091FF] text-[#0091FF] rounded-lg w-5/12 p-1 ",
                                      onClick: (function (param) {
                                          handleNavigate();
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: props.buttonText,
                                      className: "bg-[#0091FF] border border-[#0091FF] text-white rounded-lg w-5/12  p-1 ",
                                      onClick: (function (param) {
                                          handleNavigate();
                                        })
                                    })
                              ],
                              className: "flex flex-row justify-between  "
                            })
                      ],
                      className: "flex flex-col gap-6 w-11/12  max-w-md bg-white p-6 rounded-lg shadow-lg"
                    }),
                className: "absolute -inset-4 flex items-center justify-center z-50 bg-black bg-opacity-50",
                onClick: (function (param) {
                    toggleModal();
                  })
              });
  } else {
    return null;
  }
}

var make = LinkToFinternetModal;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
