// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function LoanOfferCard(props) {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "absolute right-0 z-0 -m-5",
                      alt: "Background Image",
                      src: "/BackgroundPurpleGradient.svg"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      alt: "Description of image",
                                      src: "/RoundedPinkRectangle.svg"
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "w-px h-4 bg-[#E6E6E6] self-center"
                                    })
                              ],
                              className: "flex flex-row gap-2"
                            }),
                        JsxRuntime.jsx("div", {
                              children: "ABC Bank",
                              className: "font-bold text-sm self-center"
                            })
                      ],
                      className: "flex flex-row gap-3 "
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: "Applicant Name",
                                      className: " text-lg font-light text-textGray"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: "Siddharth Shetty",
                                      className: "font-bold text-lg"
                                    })
                              ],
                              className: "flex flex-col "
                            }),
                        JsxRuntime.jsx("div", {
                              className: "border-t border-dashed w-full  border-[#E6E6E6]"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Property Value",
                                              className: "text-lg font-light text-textGray"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "₹ 1,00,00,000",
                                              className: "font-bold text-lg"
                                            })
                                      ],
                                      className: "flex flex-col "
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("div", {
                                                      children: "Loan Amount",
                                                      className: " text-lg font-light text-textGray"
                                                    }),
                                                JsxRuntime.jsx("div", {
                                                      children: "₹ 80,00,000",
                                                      className: "font-bold text-lg"
                                                    })
                                              ],
                                              className: "flex flex-col "
                                            }),
                                        JsxRuntime.jsxs("div", {
                                              children: [
                                                JsxRuntime.jsx("div", {
                                                      children: "Interest",
                                                      className: " text-lg font-light text-textGray"
                                                    }),
                                                JsxRuntime.jsx("div", {
                                                      children: "7%",
                                                      className: "font-bold text-lg"
                                                    })
                                              ],
                                              className: "flex flex-col "
                                            })
                                      ],
                                      className: "flex flex-row gap-4"
                                    }),
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              children: "Tenure",
                                              className: " text-lg font-light text-textGray"
                                            }),
                                        JsxRuntime.jsx("div", {
                                              children: "20 years",
                                              className: "font-bold text-lg"
                                            })
                                      ],
                                      className: "flex flex-col "
                                    })
                              ],
                              className: "flex flex-col gap-2"
                            })
                      ],
                      className: "flex flex-col gap-3 "
                    })
              ],
              className: "flex flex-col gap-8 relative border border-gray-100 rounded-2xl p-5 overflow-hidden "
            });
}

var make = LoanOfferCard;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
