// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function SuccessStatusWithText(props) {
  var __color = props.color;
  var color = __color !== undefined ? __color : "Green";
  var pathName;
  pathName = color === "Green" ? "/Success.svg" : "/SuccessBlue.svg";
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("img", {
                      className: "w-5/12 self-center",
                      alt: "Description of image",
                      src: pathName
                    }),
                JsxRuntime.jsx("div", {
                      children: props.text,
                      className: "font-bold self-center text-center "
                    })
              ],
              className: "flex flex-col gap-2 self-center w-9/12"
            });
}

var make = SuccessStatusWithText;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
