// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TransactionsList(props) {
  return JsxRuntime.jsx("img", {
              className: "w-full h-auto max-w-xs md:max-w-md lg:max-w-lg",
              alt: "Description of image",
              src: "/TransactionsList.svg"
            });
}

var make = TransactionsList;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
