// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Colors from "../Utilities/Colors.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function TransactionHistoryItem(props) {
  var contact = props.contact;
  var match = contact.transactionType;
  var textColor;
  textColor = match === "Credited" ? "text-green" : "text-red";
  var formatAmount = function (contact) {
    var match = contact.transactionType;
    if (match === "Credited") {
      return "+ ₹ " + contact.amount;
    } else {
      return "- ₹ " + contact.amount;
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("img", {
                                      className: "border border-white rounded-md",
                                      alt: "Description of image",
                                      src: contact.imagePath
                                    }),
                                JsxRuntime.jsx("div", {
                                      className: "w-px h-4 bg-[#E6E6E6] self-center"
                                    })
                              ],
                              className: "flex flex-row gap-2"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("div", {
                                      children: contact.name,
                                      className: "font-bold text-sm"
                                    }),
                                JsxRuntime.jsx("div", {
                                      children: contact.finternetId,
                                      className: "text-xs text-[" + Colors.colors.gray + "]"
                                    })
                              ],
                              className: "flex flex-col w-9/12"
                            })
                      ],
                      className: "flex flex-row gap-3 "
                    }),
                JsxRuntime.jsx("div", {
                      children: formatAmount(contact),
                      className: "text-xs font-bold self-center " + textColor + " "
                    })
              ],
              className: "flex flex-row justify-between mx-1"
            });
}

var make = TransactionHistoryItem;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
