// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./MobileScreens/Home.res.mjs";
import * as Login from "./MobileScreens/Login.res.mjs";
import * as React from "react";
import * as EnterPin from "./MobileScreens/EnterPin.res.mjs";
import * as Transfer from "./MobileScreens/Transfer.res.mjs";
import * as Accordion from "./Components/Accordion.res.mjs";
import * as EnterAmount from "./MobileScreens/EnterAmount.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as TransactionCompleted from "./MobileScreens/TransactionCompleted.res.mjs";

function App(props) {
  var match = React.useState(function () {
        return "Login";
      });
  var setCurrentScreen = match[1];
  var currentScreen = match[0];
  var renderContent = function () {
    switch (currentScreen) {
      case "Login" :
          return JsxRuntime.jsx(Login.make, {
                      onNavigateToHome: (function () {
                          setCurrentScreen(function (param) {
                                return "Home";
                              });
                        })
                    });
      case "Home" :
          return JsxRuntime.jsx(Home.make, {
                      onNavigateToReceiversList: (function () {
                          setCurrentScreen(function (param) {
                                return "Transfer";
                              });
                        })
                    });
      case "EnterAmount" :
          return JsxRuntime.jsx(EnterAmount.make, {
                      onNavigateToEnterPin: (function (param) {
                          setCurrentScreen(function (param) {
                                return "EnterPin";
                              });
                        })
                    });
      case "EnterPin" :
          return JsxRuntime.jsx(EnterPin.make, {
                      onNavigateToTransactionCompleted: (function (param) {
                          setCurrentScreen(function (param) {
                                return "TransactionCompleted";
                              });
                        })
                    });
      case "Transfer" :
          return JsxRuntime.jsx(Transfer.make, {
                      onNavigateToEnterAmount: (function (param) {
                          setCurrentScreen(function (param) {
                                return "EnterAmount";
                              });
                        })
                    });
      case "TransactionCompleted" :
          return JsxRuntime.jsx(TransactionCompleted.make, {
                      onNavigateToHome: (function (param) {
                          setCurrentScreen(function (param) {
                                return "Home";
                              });
                        })
                    });
      
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: renderContent(),
                      className: "bg-white h-4/5 self-center w-1/5 p-4 shadow-lg rounded-lg"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(Accordion.make, {}),
                      className: "ml-4 p-4  bg-gray-100 rounded-lg"
                    })
              ],
              className: "flex justify-center  h-screen w-screen flex-row  jc p-4 border font-space-grotesk"
            });
}

var make = App;

export {
  make ,
}
/* Home Not a pure module */
