// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: "Hello world.",
              className: "text-3xl text-center m-5 text-gray-700"
            });
}

var make = App;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
