// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Client from "react-dom/client";
import * as JsxRuntime from "react/jsx-runtime";

var rootElement = document.querySelector("#root");

if (rootElement == null) {
  Js_exn.raiseError("No element has ID of #root!");
} else {
  var root = Client.createRoot(rootElement);
  root.render(JsxRuntime.jsx(App.make, {}));
}

export {
  
}
/* rootElement Not a pure module */
